### PR TITLE
Language modifications

### PR DESCRIPTION
**Pull request by windowsboy111**
~~Do not merge yet,~~ see https://github.com/cyberos/other-issues/discussions/7#discussioncomment-738038

### CODE REVIEW

**Comment by omaemae** [comment]
github is annoying

**Comment by windowsboy111** [comment]
this goes after #8 as there are incompatible modifications.

**Comment by windowsboy111** [comment]
no longer draft
changes:
- faff around the language mappings in `translations.js`
- sort by keys in translation files
- sort the language codes in `translations.js`

**Review by windowsboy111 — COMMENTED** [review]
Can any CyberOS maintainers merge this PR?

**Comment by omaemae** [comment]
I'm not sure it works (and I'm not on my laptop to test) so could you check if it works? run `npm install` and `npm start` (or use yarn, whatever you prefer) @windowsboy111

**Comment by windowsboy111** [comment]
I just tested it, after fixing a bug (in `10f0f52`), the website is working.

**Pull request merged**
